# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: togo CI

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./server
    - name: Module Cache
      uses: actions/cache@v2.1.2
      with:
        path: ./server/node_modules
        key: NodeModules
    - run: npm run build
      working-directory: ./server
    - run: npm run test-ci
      working-directory: ./server
